name: Fetch Plan

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  fetch-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          PRODUCTION_DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
        run: |
          curl -u :$ADMIN_PASSWORD https://$PRODUCTION_DOMAIN/api/admin/fetchPlan
